### ISSUE TITLE
Use swagger file to access middleware endpoints

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-ui#1017]
https://github.com/aeternity/superhero-ui/blob/62857bff23ab868de949325c3e627c27043c7437/src/utils/middleware.js#L3-L9

See how it works in the wallet as an example:

https://github.com/aeternity/superhero-wallet/blob/92a8f0053c2bfc3fcb8506c917f33103d960412f/src/lib/wallet.js#L12-L68

cc: @thepiwo @AtanasKrondev

**Comment by thepiwo** [comment]
@AtanasKrondev can you check this?
