### ISSUE TITLE
Integrated wallet does not load in the side menu on develop

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#1025]
<img width="1435" alt="Screenshot 2021-02-23 at 14 56 51" src="https://user-images.githubusercontent.com/13139371/108846590-6b1eae00-75e7-11eb-9a9a-df083009b7bb.png">

**Comment by davidyuk** [comment]
is it Chrome in Incognito mode?

**Comment by davidyuk** [comment]
Maybe we can implement some notification on the wallet side to help a user to solve this?
