### ISSUE TITLE
Drop chainNames, cache preferredChainNames in store

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-ui#1057]
https://github.com/aeternity/superhero-ui/pull/1055/files#diff-0852536b2db287d3b6f0554e8a569b565a195d1075aa93dd8bf019dad51e6138R70-R73

cc: @AtanasKrondev

**Comment by AtanasKrondev** [comment]
https://github.com/aeternity/superhero-ui/pull/1065#pullrequestreview-686028371
