### ISSUE TITLE
Add proper meta tags

### ISSUE THREAD

**Issue by kenodressel** [aeternity/superhero-ui#1090]
Tips:

- add proper title (og:title) --> should be "Superhero Tip <ID>_v?"
- add proper image: (og:image) --> should be the media url if its a post without tip, otherwise use the profile picture of the tip creator
- add proper description: (og:description) --> should be the tips text

Comments:

- "Superhero Comment <ID>_v?"
- add proper image: (og:image) --> the profile picture of the comment creator
- add proper description: (og:description) --> should be the comment text

**Comment by paolomolo** [comment]
I would recommend adding following additional meta tags:
- name="twitter:card" --> same image as og:image
- property="og:site_name" --> probably just "Superhero" (see link below)
- name="twitter:image:alt" --> alt image description for screen readers

Please see https://css-tricks.com/essential-meta-tags-social-media/ for further how to use them.
