### ISSUE TITLE
Error when trying to tip on superhero.com/meet

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-ui#1132]
I get this error when trying to tip on superhero.com/meet, both when clicking on the avatar icon and chat icon

![5555](https://user-images.githubusercontent.com/69896204/124624458-8fd43d80-de85-11eb-8fcb-4616e980fd5c.png)

@venimus could you please check this?

**Comment by venimus** [comment]
issue fixed in https://github.com/aeternity/jitsi-meet/releases/tag/v1.6.0
