### ISSUE TITLE
Tip section is shown without having active account in wallet

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#171]
The tip section is shown when user has installed the superhero wallet but has not yet created a keypair.

I think this should not be the case - meaning it should be only shown when the wallet is ready for tipping.

Currently this results to:

<img width="1431" alt="Screenshot 2020-03-19 at 13 00 43" src="https://user-images.githubusercontent.com/13139371/77060860-efcd7900-69e1-11ea-8e08-2e1c6c87e146.png">

**Comment by etharner** [comment]
@mradkov Shouldn't this issue be closed now?
