### ISSUE TITLE
Comment input design inconsistency

### ISSUE THREAD

**Issue by venimus** [aeternity/superhero-ui#216]
![image](https://user-images.githubusercontent.com/632282/77416857-1bc77080-6dcd-11ea-9ee4-df76b2802990.png)

Should be:
* Desktop
![image](https://user-images.githubusercontent.com/632282/77416885-27b33280-6dcd-11ea-88bf-4c77f727a17d.png)

* Mobile:
![image](https://user-images.githubusercontent.com/632282/77416925-3dc0f300-6dcd-11ea-964c-4accf49aabea.png)

Note: Button text / label/ placeholder should say Reply instead of Comments

**Comment by stanislav-slavov** [comment]
The desktop version needs a button to submit the comment.

**Comment by venimus** [comment]
Yes, designers decision

Put the button bellow as in other forms (Should say Reply)

![image](https://user-images.githubusercontent.com/632282/77467453-b4cdaa00-6e14-11ea-8422-5bd8e0b1f725.png)

**Comment by mradkov** [comment]
Whats the status of this @venimus @stanislav-slavov

**Comment by stanislav-slavov** [comment]
The current state of the input is:
- It expands as the user types.
- The button is inside the input and appears only when there is any content written.
- When pressing enter the content is submitted 

The only thing that's remaining from this issue is the arrow on the left side of the input.

**Comment by mradkov** [comment]
> The current state of the input is:
> 
>     * It expands as the user types.
> 
>     * The button is inside the input and appears only when there is any content written.
> 
>     * When pressing enter the content is submitted
> 
> 
> The only thing that's remaining from this issue is the arrow on the left side of the input.

Lets finalize this then.
