### ISSUE TITLE
Change the "fallback image" to represent the new logo

### ISSUE THREAD

**Issue by venimus** [aeternity/superhero-ui#333]
![image](https://user-images.githubusercontent.com/632282/78973870-6b21d680-7b19-11ea-8e12-d1983a0a8c1b.png)

**Comment by CedrikNikita** [comment]
![image](https://user-images.githubusercontent.com/9008074/79537012-acd7f180-80c4-11ea-96cc-2bb2522302db.png)
Already fixed in develop branch
