### ISSUE TITLE
Fix visual issues in UserProfile

### ISSUE THREAD

**Issue by venimus** [aeternity/superhero-ui#334]
Match the current design (spacings) and the Edit profile button style

**Comment by CedrikNikita** [comment]
@venimus About spacing i have a question (cause as i know we have only one screen with My profile).
What should be done in case we dont have a .chain name?
![image](https://user-images.githubusercontent.com/9008074/80182073-6c8aed00-8649-11ea-9318-e0390bda0168.png)
