### ISSUE TITLE
Fix focused state of inputs

### ISSUE THREAD

**Issue by venimus** [aeternity/superhero-ui#338]
Border color should be blue
![image](https://user-images.githubusercontent.com/632282/79007616-31c28880-7b64-11ea-8f0b-828ddf61845a.png)

also Inputs are different heights (should be 44px 2.2rem)

![image](https://user-images.githubusercontent.com/632282/79007849-ba412900-7b64-11ea-8109-7faa8c65b6ff.png)

**Comment by CedrikNikita** [comment]
1. What kind of blue? this one #2a9cff
2. Should retip inputs also be with a blue border?

**Comment by venimus** [comment]
> @venimus Issue almost done except for this questions.
> 
> 1. What kind of blue? this one #2a9cff
> 2. Should retip inputs also be with a blue border?

yes to both
