### ISSUE TITLE
Infinite scroll on "zoomed" (125%) page not triggered

### ISSUE THREAD

**Issue by venimus** [aeternity/superhero-ui#349]
It seems a minor issue but when page is zoomed-in (enlarged) more than 100% (i.e. 125%) the page scroll does not trigger the new page fetching. It is often a common case to zoom-in on large (high-dpi) monitors.
As soon as you switch back to 100% loading of the next page is triggered instantly.

**Comment by CedrikNikita** [comment]
Ifinite scroll doesn't work on <67% aswell and all enlargement
