### ISSUE TITLE
Comment Input box should be at the bottom

### ISSUE THREAD

**Issue by kenodressel** [aeternity/superhero-ui#35]
![image](https://user-images.githubusercontent.com/765921/75759849-7de50680-5d36-11ea-82ce-a9a6ad8fc6aa.png)

**Comment by kenodressel** [comment]
We should discuss this with the design team but I think its bad practice

**Comment by mradkov** [comment]
> We should discuss this with the design team but I think its bad practice

I guess it will not be user friendly to have it on the bottom.. if there are lots of items in the list of comments.

**Comment by davidyuk** [comment]
Having the new comment form at the bottom may motivate the user to read existing comments before creating a new one. 🤷‍♀️

**Comment by kenodressel** [comment]
I agree but I also think that the comments here are not nessesarely to be viewed as a "thread" but rather as responses to the first post. Therefore I would suggest we do not implement this change for now. @mradkov should communicate this to yani.
