### ISSUE TITLE
Remove/Replace Create Profile

### ISSUE THREAD

**Issue by venimus** [aeternity/superhero-ui#403]
Contents should be rephrased as FAQ sections
Menu navigation should not appear for not logged in users or use something less confusing like Install wallet tutorial

**Comment by mradkov** [comment]
Create profile should not be removed, rather lead to installing wallet or ?

**Comment by venimus** [comment]
May be we can create (rename it to) a "Install the wallet" page or something and put some info there for how to do that (extract text from FAQ and style it a little)

**Comment by stanislav-slavov** [comment]
Create-Profile page is styled exactly as the FAQ page. Also has the same expandable panels with informative sections. As far as I understand the requirement - we should rename the Create Profile link to "Install the wallet"
