### ISSUE TITLE
Infinite scroll doesn't work if you choose My profile first

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/superhero-ui#427]
![Scroll bug](https://user-images.githubusercontent.com/9008074/80583003-fd4f3780-8a52-11ea-9686-4f7a5ed4ec2a.gif)

**Comment by venimus** [comment]
May be related to the other issue #349

**Comment by CedrikNikita** [comment]
it is not

**Comment by mradkov** [comment]
Could be the `keep-alive` ? 🤔
