### ISSUE TITLE
Trending section breaks if longer tip amount

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#462]
<img width="401" alt="Screenshot 2020-05-05 at 8 14 18" src="https://user-images.githubusercontent.com/13139371/81036632-795cdb80-8ea8-11ea-9d49-b42ddfbe4f2c.png">

**Comment by vmangelovv** [comment]
As the currency is replaced with its symbol the long amount is not breaking the line in Trendings anymore. #465
