### ISSUE TITLE
incorrect identicon is shown if user profile is not connected yet.

### ISSUE THREAD

**Issue by thepiwo** [aeternity/superhero-ui#489]

**Comment by mradkov** [comment]
This should be to a degree resolved by #531. I think we need some default avatar for the form there if no logged in account is present.

**Comment by thepiwo** [comment]
If there is no logged in account, why show the form

**Comment by mradkov** [comment]
> If there is no logged in account, why show the form

It works with the web-wallet via deeplinks if there is no logged wallet.

**Comment by thepiwo** [comment]
good point, so we need a default, or better for without identicon. But I guess it should not "bug" or change when logging in properly
