### ISSUE TITLE
Form is blocked if no account active

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#505]
The form should allow to be filled if there is no active account - deeplink to the web wallet.

<img width="637" alt="Screenshot 2020-05-15 at 9 44 55" src="https://user-images.githubusercontent.com/13139371/82019916-bc7d3280-9690-11ea-9904-9332a7aaa7b6.png">

**Comment by stanislav-slavov** [comment]
As discussed, if the user is not logged, the collapsed "send tip" section will point to the wallet "tip" action upon click.
