### ISSUE TITLE
Loading flagged content

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#569]
Probably there should be a check if the tip
was flagged and if the show flagged is on to prevent this from happening. As fallback there could be a redirect in place to the main feed.

_Originally posted by @mradkov in https://github.com/aeternity/superhero-ui/pull/534#issuecomment-635117607_

**Comment by stanislav-slavov** [comment]
The problem is that the request will not return the tip because the json response is invalid. We could just catch the error and display error message.

**Comment by mradkov** [comment]
Why is it invalid?

**Comment by stanislav-slavov** [comment]
It could not be parsed to json, probably its structure is wronged.

**Comment by mradkov** [comment]
@kenodressel can you take a look?

**Comment by kenodressel** [comment]
@stanislav-slavov What endpoint are we talking about?

**Comment by stanislav-slavov** [comment]
The problem could be seen with this tip: https://stage.youdonotneedacapetobeahero.com/#/tip/1160

In this case it is: cache/tip?id=${id}
But if the issue is related to the flagged content it may occur in other places.

**Comment by kenodressel** [comment]
Ah! So right now, by default, flagged content is hidden. Should we change this?
Additionally it looks like we got a bug here as well since the backend should return the tip here, as I think blacklisting would only apply to lists from now on and not for single tips.

**Comment by stanislav-slavov** [comment]
I guess the flagged content should be hidden by default, only if the user wants to see it one should get it. The point was to hide the inappropriate posts from main feeds.

**Comment by kenodressel** [comment]
I made a new pr https://github.com/aeternity/tipping-community-backend/pull/130. The behavior is now as follows:
- if requesting a specific tip (eg. id 1160) the backend ignores blacklisting
- if requesting the full list by default blacklisted items are not shown
- if requesting a non existing tip, the backend will now return 404

**Comment by stanislav-slavov** [comment]
Looks good!

**Comment by mradkov** [comment]
@kenodressel @stanislav-slavov can you confirm this is fixed with https://github.com/aeternity/tipping-community-backend/pull/130?

**Comment by stanislav-slavov** [comment]
> @kenodressel @stanislav-slavov can you confirm this is fixed with [aeternity/tipping-community-backend#130](https://github.com/aeternity/tipping-community-backend/pull/130)?

I can no longer reproduce it. It is fixed.
