### ISSUE TITLE
Plan referral feature

### ISSUE THREAD

**Issue by thepiwo** [aeternity/superhero-ui#58]

**Comment by kenodressel** [comment]
Motivation:
- The communications team would like to reward users for sharing the platform with their peers with tokens.
Technically possible path:
- Backend generates referral link for a certain user
- User visits site over referral link
- Referral token is set in cookie / local storage --> potential GDPR issues?
- User interacts with the page, downloads wallets etc
- At some point he will cross a threshold (eg. 10 AE spent) and then a request is send to the backend
- the backend verifies that all conditions are met and sends the grant to the users account

**Comment by thepiwo** [comment]
already implemented
