### ISSUE TITLE
Avoid unobvious rendering management in AvatarWrapper

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-ui#603]
Well, I see that it is a kind of workaround for showing an actual user avatar. I'm not sure about all edge cases, but I think I found a good solution for the user's [own avatar](https://github.com/aeternity/superhero-ui/pull/597/commits/ef24c71a7d9671af506d42d24ca10ef2268a62e7#diff-56300217d84b9be69bdb4e418875952aR323-R325). Is it the only case when the avatar was not displayed properly? Can we use my solution instead?

**Comment by mradkov** [comment]
Is this fixed with https://github.com/aeternity/superhero-ui/pull/597?

**Comment by davidyuk** [comment]
nope
