### ISSUE TITLE
Some user profiles return 404 from the backend

### ISSUE THREAD

**Issue by venimus** [aeternity/superhero-ui#626]
Some user profiles return 404 from the backend
https://superhero.com/user-profile/ak_2ExMzdRYsGGGndBgrm7UjNB6WTAvGEV3R5VdPXfhFpXcZVtzGi
altough they have tips

![image](https://user-images.githubusercontent.com/632282/83931776-2330d000-a7a7-11ea-80da-2f815cd3fbcd.png)

![image](https://user-images.githubusercontent.com/632282/83931831-7440c400-a7a7-11ea-8ab8-855c1de11967.png)

**Comment by mradkov** [comment]
Fixed with #625
