### ISSUE TITLE
Join Date Broken

### ISSUE THREAD

**Issue by kenodressel** [aeternity/superhero-ui#651]
**Describe the bug**
Some profiles join dates are broken right now.  For example:
https://superhero.com/user-profile/ak_2KuGHYNdSxdfBNxRfxHPFmJ2zr7T7TQog5heuXkvDtLEj9XmzH
which shows: 
![image](https://user-images.githubusercontent.com/765921/85000467-bcba9300-b152-11ea-8973-1c7174fb7205.png)

**To Reproduce**
1. Go to https://superhero.com/user-profile/ak_2KuGHYNdSxdfBNxRfxHPFmJ2zr7T7TQog5heuXkvDtLEj9XmzH

**Desktop (please complete the following information):**
 - OS: Linux 5.4
 - Browser Firefox
 - Version 77

**Comment by mradkov** [comment]
Only reproduce-able on FF. Thanks for the report.

<img width="462" alt="Screenshot 2020-06-18 at 13 43 28" src="https://user-images.githubusercontent.com/13139371/85011117-c7345700-b169-11ea-9bcd-88afd24616c1.png">
