### ISSUE TITLE
Avoid wrapping of RouterView with KeepAlive

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-ui#664]
As I see in 6b33f1e3ba72e75ac5d5b1e61c89e85e2443a05f, it was made to preserve loaded data and more easily restore scroll position. It makes Vue behave less obviously (https://github.com/aeternity/superhero-ui/pull/659/files#r445270616), I propose to pass displayed data through Vuex, it will allow to cache it and to make components not aware of data fetching and be more stateless.

**Comment by shapkarin** [comment]
Please, have a look at that review https://github.com/aeternity/superhero-ui/pull/659#pullrequestreview-437117148
I'm agree that Vuex will make the whole app more predictable.
