### ISSUE TITLE
Remove lodash required by our dependency from bundle

### ISSUE THREAD

**Issue by shapkarin** [aeternity/superhero-ui#693]
I think we can import lodash packages directly or use some webpack loader.

Like
```js
import times from 'lodash/times'
// instead of
import { times } from 'lodash' 
```

upd:
for example we can use https://www.npmjs.com/package/babel-plugin-lodash

**Comment by shapkarin** [comment]
https://www.npmjs.com/package/babel-plugin-lodash

**Comment by davidyuk** [comment]
why don't use `lodash-es` instead? it uses es6 `imports`/`exports` that can be tree shaked.
So `import { times } from 'lodash-es'` should work fine.

**Comment by davidyuk** [comment]
`avataaars` package depends on `lodash`, probably because of it lodash is in our [bundle](https://feature-refactor-tips-pagination.aggregator.z52da5wt.xyz/report.html)

**Comment by shapkarin** [comment]
@davidyuk thanks a lot for the info. Didn't know about `lodash-es` 
But, yes, I saw the lodash at the analyzer.

Not sure part of what it is:
<img width="1200" alt="Снимок экрана 2020-07-07 в 13 12 43" src="https://user-images.githubusercontent.com/1463086/86766760-a7e76600-c053-11ea-91b6-153baf6d9dc4.png">

**Comment by davidyuk** [comment]
Well, as I see superhero-ui explicitly imports only `lodash-es`.

**Comment by shapkarin** [comment]
I will leave it closed by now

**Comment by davidyuk** [comment]
I propose to keep it open until we find the package that imported lodash into our bundle and consider an alternative to that package.

**Comment by davidyuk** [comment]
Somewhere we have lose the extra lodash, so I'm closing this issue (thanks to @CedrikNikita)
