### ISSUE TITLE
Reduce the amount of styles in base.scss

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-ui#696]
For instance, there defined a `.filter-button` that is used only in ListOfTipsAndComments

**Comment by stanislav-slavov** [comment]
It is also used in the Time Back Machine(still not merged) and looks like a standard filtering button in our design.

**Comment by davidyuk** [comment]
Ok, does it have the sense to extract it into a separate component? I think to track component usage is easier than globally-defined classes (also unused components will be tree-shaked).

**Comment by stanislav-slavov** [comment]
> Ok, does it have the sense to extract it into a separate component? I think to track component usage is easier than globally-defined classes (also unused components will be tree-shaked).

Agree. I will extract it into a separate component and re-use it in the time back machine. 

Is this the scope of this issue - refactor .filter-button into a separate reusable component?

**Comment by davidyuk** [comment]
I have not checked the whole `base.scss`, maybe there is something like this. In general, I would suggest reducing the amount of global styles and to put them in corresponding components instead (marking them with `scoped`).
