### ISSUE TITLE
Fix all exceptions and warnings in developer console after initial load

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-ui#703]
![Screenshot 2020-07-09 at 15 12 49](https://user-images.githubusercontent.com/9007851/86999731-a7d39b80-c1f6-11ea-966b-2c2981bad9aa.png)

- [x] fix Avatars package related problems
- [x] fix other problems
except for 404's they can't be avoided

**Comment by CedrikNikita** [comment]
In the current stage of develop, there is no such issues. This issue will be closed, feel free to reopen it if the issue will persist in the future releases.
