### ISSUE TITLE
Scrolled position is lost if you click on other navigation, then click `Tips` in navigation 

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/superhero-ui#715]
https://github.com/aeternity/superhero-ui/pull/708#pullrequestreview-447750491

**Comment by venimus** [comment]
I think this is an expected behavior, to allow users to easier refresh and go to top with the latest updates. Similar way it works on other social networks

**Comment by etharner** [comment]
@mradkov should we close this then?
