### ISSUE TITLE
Meet tab still works not as expected

### ISSUE THREAD

**Issue by shapkarin** [aeternity/superhero-ui#723]
This pr #722 fixed some issues but this page still has some bugs. 
Reproduce:
- create a room by choosing one from the rooms names list
- we are still at the same superhero page
- click the meet tab, still on the same page because at first step route was not changes

maybe ref to https://github.com/aeternity/jitsi-meet/issues/115 because page reloads

look at https://github.com/aeternity/jitsi-meet/blob/3144c031a50358850d4ae1f37c4fbbc1f817f4f1/react/features/recent-list/components/AbstractRecentList.js#L97-L103

**Comment by shapkarin** [comment]
UPD: the issue have different nature. it's only when user click to the rooms list.

**Comment by shapkarin** [comment]
may be ref to https://github.com/aeternity/jitsi-meet/issues/115
because page reloads

**Comment by venimus** [comment]
i can't reproduce misbehavior, can you elaborate what is expected

**Comment by shapkarin** [comment]
It’s can be reproduced only if you create room by click at the rooms from
history, the list under the input.

**Comment by venimus** [comment]
i see, but i found that the history list does not appear in the stage server for some reason

**Comment by shapkarin** [comment]
I guess that depends on how much rooms you create by yourself.

**Comment by shapkarin** [comment]
this PR fix it https://github.com/aeternity/jitsi-meet/pull/118

**Comment by mradkov** [comment]
> this PR fix it [aeternity/jitsi-meet#118](https://github.com/aeternity/jitsi-meet/pull/118)

I guess we can close this issue as it is fixed on jitsi side?

**Comment by shapkarin** [comment]
Yes, now I fixed typo and pass CI, so it's merged
