### ISSUE TITLE
Jitsi Meet integration: Use an integrated postMessage api instead of SDK

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-ui#728]
External API have a [`dispose`](https://github.com/aeternity/jitsi-meet/blob/2e2d40c1d0c288d37551654a4f84f124d501179b/modules/API/external/external_api.js#L606-L618) method I think we should call it before creating a new instance/closing of meet page.

Also, there is a [`videoConferenceJoined`](https://github.com/aeternity/jitsi-meet/blob/2e2d40c1d0c288d37551654a4f84f124d501179b/modules/API/external/external_api.js#L568-L573) event, can we use it instead of a custom [setup depending on sdk](https://github.com/aeternity/superhero-ui/blob/d335355d1e6ea75b4f226027187c83fca0929ce1/src/views/Conference.vue#L36-L46)?

cc: @shapkarin

**Comment by shapkarin** [comment]
Thanks!

**Comment by shapkarin** [comment]
> Also, there is a videoConferenceJoined event, can we use it instead of a custom setup depending on sdk?

I can't use it now.

**Comment by shapkarin** [comment]
@davidyuk I can't use that event until we have Prejoin screen and it's not emmits at that screen. Also it's some buggy.. not sure why. But can remove the `closes` words from PR and commit and check that later again.

**Comment by mradkov** [comment]
> @davidyuk I can't use that event until we have Prejoin screen and it's not emmits at that screen. Also it's some buggy.. not sure why. But can remove the `closes` words from PR and commit and check that later again.

@shapkarin can you revisit this?

**Comment by shapkarin** [comment]
@mradkov OK, First I will finish with https://github.com/aeternity/jitsi-meet/issues/228 abd next I will try to replace sdk post message tools with jitsi [videoConferenceJoined](https://github.com/aeternity/jitsi-meet/blob/2e2d40c1d0c288d37551654a4f84f124d501179b/modules/API/external/external_api.js#L568-L573) to share the room name with superhero

**Comment by shapkarin** [comment]
@mradkov OK a little bit later I will try to replace sdk post message tools with jitsi [videoConferenceJoined](https://github.com/aeternity/jitsi-meet/blob/2e2d40c1d0c288d37551654a4f84f124d501179b/modules/API/external/external_api.js#L568-L573) to share the room name with superhero

**Comment by davidyuk** [comment]
It is not necessary to use exactly `videoConferenceJoined` event, but just to emit something through a predefined interface instead of using messaging from sdk.

**Comment by shapkarin** [comment]
> It is not necessary to use exactly `videoConferenceJoined` event, but just to emit something through a predefined interface instead of using messaging from sdk.

@davidyuk I understand your opinion and agree to avoid js-sdk's BrowserWindowMessageConnection. Just didn't have mutch attention and time for that. Thanks for notify and will try to find a time soon.

**Comment by shapkarin** [comment]
@davidyuk look like it's not possible because jitsi is not sends any postMessages also listener is not fired at all.

**Comment by davidyuk** [comment]
Can you send a message with the room name manually from Meet's side using the predefined Meet's interface instead of js-sdk?

But, actually, I'm not sure that we shouldn't spend so long time on that, I was just proposing to make it a bit more accurate assuming that you are aware of internal Meet's structure.

**Comment by shapkarin** [comment]
done
