### ISSUE TITLE
"Safe content only" shows additional posts instead of removing them

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-ui#729]
On https://develop.aggregator.z52da5wt.xyz/:

![Screenshot 2020-07-24 at 13 02 02](https://user-images.githubusercontent.com/9007851/88357219-df714480-cdad-11ea-89b6-de4fd0538afc.png)
![Screenshot 2020-07-24 at 13 02 10](https://user-images.githubusercontent.com/9007851/88357224-e4ce8f00-cdad-11ea-8d79-7cafde40bdc9.png)

**Comment by mradkov** [comment]
I think this is just the ordering that is different and that's why you see them as "new".

**Comment by etharner** [comment]
@mradkov should we close this?
