### ISSUE TITLE
What is the status of Bootstrap in this project?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-ui#740]
How actively it is planned to use it?

Removing of bootstrap-vue in #682 looks like that Bootstrap is more in the deprecated state, is it true?

From my perspective, it makes styles messier especially when Bootstrap styles overrides: https://github.com/aeternity/superhero-ui/blob/bda0e1d51f004d8a527063c35d7f7d5595f19938/src/components/SendComment.vue#L109-L110

Also, I can't use short and semantic classes like `modal` or `row` because they overlap with global bootstrap styles.

**Comment by mradkov** [comment]
> Removing of bootstrap-vue in #682 looks like that Bootstrap is more in the deprecated state, is it true?

It's in a deprecated state. Though there is a bootstrap dependency in the Time-back machine date picker (maybe we can refactor it to use custom or some other pickers).
