### ISSUE TITLE
No any links to mission page

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-ui#747]
Is it still needed? Maybe we can remove it?

**Comment by mradkov** [comment]
Isn't there an internal link from the FAQ to the mission page? 🤔

**Comment by davidyuk** [comment]
I think the last link to Mission was removed in https://github.com/aeternity/superhero-ui/commit/f23cd5863a61f12ffb2c199c053311279b7dce9b#diff-fa32d5cc2925a239c7adafd08c600d38L30-L37 because that slot wasn't used in locales.

**Comment by etharner** [comment]
@mradkov can we close this?

**Comment by davidyuk** [comment]
@etharner wh are you proposing to close this?

Let's remove the mission page! 🚀

**Comment by mradkov** [comment]
Let's not remove it. Still waiting for comms team to provide resources and content for those pages.

**Comment by davidyuk** [comment]
Ok, let's wait for it, but technically this issue is still actual
