### ISSUE TITLE
Tip amount not visible if no preview is fetched

### ISSUE THREAD

**Issue by kenodressel** [aeternity/superhero-ui#765]
If there is no preview available (for new tips or due to backend issues) the tip amount is not displayed.
![image](https://user-images.githubusercontent.com/765921/90494472-d3299e80-e143-11ea-9614-21b720079a88.png)

**Comment by AtanasKrondev** [comment]
Is it still viable issue?

**Comment by mradkov** [comment]
I think this will be automatically resolved with https://github.com/aeternity/tipping-community-backend/pull/172. Correct me if I'm wrong @kenodressel

**Comment by kenodressel** [comment]
Happy to correct you :) It will be less of a problem but there is still a number of tips we are unable to parse so the fallback is still relevant.
