### ISSUE TITLE
Tips not rendered correctly

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#767]
![8cf8b7ba-a3cb-443d-899d-bc655aa901c0](https://user-images.githubusercontent.com/13139371/90773690-f64c7d80-e2fe-11ea-8d5e-5572a1f2f77d.png)

Could be because of lack of preview returned by the backend? cc @kenodressel

**Comment by mradkov** [comment]
https://superhero.com/tip/1806
 https://superhero.com/tip/1803
 https://superhero.com/tip/1804

**Comment by davidyuk** [comment]
Is it build according to designs? As I see, the amount of tips should be displayed also outside of the preview area:

![Screenshot 2020-08-24 at 16 03 21](https://user-images.githubusercontent.com/9007851/91009167-56a32e00-e623-11ea-897d-36494a2d5bb2.png)

Also, there is a question about it: should the amount of tips in preview be always the same as outside of preview?

**Comment by mradkov** [comment]
> Is it build according to designs? As I see, the amount of tips should be displayed also outside of the preview area:
> 
> 
> 
> ![Screenshot 2020-08-24 at 16 03 21](https://user-images.githubusercontent.com/9007851/91009167-56a32e00-e623-11ea-897d-36494a2d5bb2.png)
> 
> 
> 
> Also, there is a question about it: should the amount of tips in preview be always the same as outside of preview?

The design you are looking at is outdated. 

Only one tip amount is to be present now - the one inside the preview box. It represents the aggregated sum of tips value to that URL.

**Comment by etharner** [comment]
@mradkov Is it still a viable issue?

**Comment by mradkov** [comment]
This should be closed. It will be handled on the backend side by https://github.com/aeternity/tipping-community-backend/pull/172
