### ISSUE TITLE
TipRecord: Styles on max-width: 480px doesn't apply on Avatar component

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/superhero-ui#769]
|  With styles |  Without  |
|---|---|
|  ![image](https://user-images.githubusercontent.com/9008074/91253712-d48e4300-e7a3-11ea-9e65-dc5364a1a6ac.png) | ![image](https://user-images.githubusercontent.com/9008074/91253753-ecfe5d80-e7a3-11ea-8f41-c4e20cbb96a7.png)|

**Comment by davidyuk** [comment]
Why they should be applied? 🤔
