### ISSUE TITLE
Choose between two strings about the same state

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/superhero-ui#778]
One of them is not used right now
https://github.com/aeternity/superhero-ui/blob/bd8494f705c1e9928e580f12ed2b7da6d6918109/src/locales/en.json#L270
https://github.com/aeternity/superhero-ui/blob/bd8494f705c1e9928e580f12ed2b7da6d6918109/src/locales/en.json#L276

**Comment by davidyuk** [comment]
I think these two messages should have the same path, not depending on a view name.

**Comment by paolomolo** [comment]
`There are no comments at the moment. ` should be used. Thanks!
