### ISSUE TITLE
Make AuthorAndDate component looks the same in all cases

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/superhero-ui#779]
@onvisions @mradkov @davidyuk this is a continuation of the [previous discussion](https://github.com/aeternity/superhero-ui/pull/771#discussion_r477321797)

![image](https://user-images.githubusercontent.com/9008074/91535198-1f4fbc80-e956-11ea-85d6-95a180a3bdb7.png)
https://develop.aggregator.z52da5wt.xyz/tip/1818

**Comment by davidyuk** [comment]
or even https://develop.aggregator.z52da5wt.xyz/tip/1818

**Comment by onvisions** [comment]
I don't see specific need to have different display of this element in the case you describe above. For the nested comments/replies though I think that displaying the whole address with the same font-szie won't be proper (regarding the smaller space) so it should be modified either with decreasing the font-size or better in my opinion by cuting it with ellipsis.
