### ISSUE TITLE
Provide new wording for successful/unsuccessful claiming attempt

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/superhero-ui#781]

**Comment by thescientress** [comment]
We will do a full run-through of the app and web tools for content checking.  Will get on this asap.

**Comment by kenodressel** [comment]
@CedrikNikita could you post the current wording in here, so @paolomolo can review them.

**Comment by paolomolo** [comment]
Success:
`Your claim was sent`
`If your claim is successful, the tip amount will be added to your wallet.`

<img width="495" alt="image" src="https://user-images.githubusercontent.com/17276821/131503600-e793f5a5-b4a3-4a8c-af78-e23258ea2cdc.png">

Error:
`Your claim could not be sent`
`Please try again later or contact support.`
