### ISSUE TITLE
Unable to send comments

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/superhero-ui#787]
```
backend.js:5 POST https://raendom-backend.z52da5wt.xyz/comment/api/ 400
util.js:20 Error: Request failed with 400
    at util.js:17
```

**Comment by mradkov** [comment]
<img width="511" alt="Screenshot 2020-09-02 at 10 06 53" src="https://user-images.githubusercontent.com/13139371/91942698-081d2000-ed04-11ea-875f-daa1334ffde8.png">


I just did 🤔

**Comment by CedrikNikita** [comment]
To reproduce try to leave a comment on this [tip](https://stage.youdonotneedacapetobeahero.com/tip/1848)
```
util.js:20 Error: Request failed with 500
    at util.js:17
```

![image](https://user-images.githubusercontent.com/9008074/92191646-a4cbf300-eea7-11ea-9b6f-d8a909334b62.png)

**Comment by kenodressel** [comment]
Are you sending an empty string as parentId? we only check if the field is defined or not, if its defined we try to find the parentId

**Comment by CedrikNikita** [comment]
> Are you sending an empty string as parentId? we only check if the field is defined or not, if its defined we try to find the parentId

Yes.
https://github.com/aeternity/superhero-ui/blob/develop/src/components/SendComment.vue#L27
https://github.com/aeternity/superhero-ui/blob/develop/src/views/TipsAndComments.vue#L22
https://github.com/aeternity/superhero-ui/blob/develop/src/views/TipsAndComments.vue#L71

**Comment by kenodressel** [comment]
Hm but the parentId default of `undefined` looks good to me tbh.
