### ISSUE TITLE
Tips without previews are not displayed good

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#789]
The backend does not return preview for some tips. @kenodressel 

<img width="661" alt="Screenshot 2020-09-02 at 10 47 58" src="https://user-images.githubusercontent.com/13139371/91953853-f3dc2180-ed09-11ea-86ed-aa7d3999830b.png">
https://superhero.com/tip/1833

**Comment by kenodressel** [comment]
failReason: "INVALID_URL, Need to provide a valid URL."
Its missing a protocol :/

**Comment by mradkov** [comment]
I see its missing protocol, but cant we prepend https:// by default if there is none provided - and crawl for preview?

**Comment by kenodressel** [comment]
I agree, I made an issue in the backend. I guess we can close this now.
