### ISSUE TITLE
FAQ expandable sections don't show the text below the title

### ISSUE THREAD

**Issue by stanislav-slavov** [aeternity/superhero-ui#807]
<img width="584" alt="Screenshot 2020-09-18 at 12 00 01" src="https://user-images.githubusercontent.com/7085525/93579278-f6e03e80-f9a6-11ea-81ae-8a1471f53daa.png">

**Comment by mradkov** [comment]
While investigating the issue it turned out this is broken because of the new _force PascalCase eslint rule_ (https://github.com/aeternity/superhero-ui/commit/620a5a75ecf77966afec40ce5a92279b4be0b922).

The `i18n` elements are being auto-converted to `I18n` which fails them to work properly.
