### ISSUE TITLE
Wrong Link redirection from superhero.com feed

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-ui#815]
When I clicked on a post there are wrong URL redirection (again on sh feed). Also no preview available for this post:

https://feature-rich-content-preview.aggregator.z52da5wt.xyz/tip/Ethkids.io

![Знімок екрана 2020-09-30 о 11 40 34 дп](https://user-images.githubusercontent.com/69896204/94665390-bec8ec00-0314-11eb-9d6c-3d81f9df1bf5.png)

Browsers: Chrome, Firefox
OS: iOS

**Comment by AtanasKrondev** [comment]
It is fixed in 37064f633a9e639d50475ec34a0b1d709af81c3d
The https:// prefix is added if missing in the url

**Comment by davidyuk** [comment]
Is this problem on develop or a feature branch? If on develop then it should be closed only when the fix is merged to develop. Otherwise, this issue should be a review for #806
