### ISSUE TITLE
UI/UX bug in mobile preview

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-ui#816]
I found this UI bug in a mobile browser. Profile information is slightly cropped:

![Знімок екрана 2020-09-30 о 3 00 43 пп](https://user-images.githubusercontent.com/69896204/94685614-5983f380-0332-11eb-976e-d1f033afe5e8.png)

**Comment by AtanasKrondev** [comment]
Fixed in 59a0a1118a8129c1340c5b58419190e1a11f21ae
