### ISSUE TITLE
User profile page filter font-size is too large (inconsistency with other UI elements)

### ISSUE THREAD

**Issue by onvisions** [aeternity/superhero-ui#823]
@mradkov @AtanasKrondev, we should fix these as soon as we have time. 

**Describe the bug**
Design inconsitencies and visual bugs.
- User profile filters font size is too large. 
- Balance and Joined are not displayed aligned to bottom of user avatar (check margins according to design provided).
Where is **Location**? Should implement this also within user profile settings (auto filled by geo location tracking if available).
- Extended options and date of the tip (within a feed item) are not displayed according to design (2 lines). 
- Within the tip view we display Fellow superhero when .chain name is missing (such as on the user profile page).

**To Reproduce**
Go to User Profile Page.

**Expected behavior**
FIlters style should be consistent with the other similar Superhero UI elements such as filters on home page (currently "Tips").
Other issues are described in the screenshot below.

**Screenshots**
![Screenshot(32)](https://user-images.githubusercontent.com/12225410/95194412-ea007f00-07dd-11eb-8ca7-26496764aaf2.png)

**Comment by mradkov** [comment]
resolved by #834
