### ISSUE TITLE
Tips unclaimed should be not visible in public user profile (only in private view for the tips owner)

### ISSUE THREAD

**Issue by onvisions** [aeternity/superhero-ui#824]
@mradkov , this should be communicated also with Max (so he needs also access to github).
**Describe the bug**

**Unclaimed tips** amount is supposed to be displayed only in the private user profile. Public user profile displays only **tips claimed** and **tips sent** amounts. There was clear difference in Public and Private User profile views in the designprovided.

**To Reproduce**
Go to User Profile page. 
See info displayed and screenshot provided below. Compare with design provided.

**Expected behavior**

- **Unclaimed Tips** amount should be hidden in the public user profile (also in the ID card public mode). Unclaimed tips amount for a specific user is not something very interesting to other users and also it might be considered sensitive/private/confidential information by the tips owner.

- **Unclaimed tips** amount on the other hand should be available as information to the tips owner when the user is viewing his/her own profile.

_Additionally it should also be a link to all unclaimed tips listed within the central column, with filtering options and force claim button. Probably a feature request with specs has to be created about this._

**Screenshots**
![Screenshot(34)](https://user-images.githubusercontent.com/12225410/95197590-8036a400-07e2-11eb-8c97-69bf7c1fc79b.png)

**Comment by mradkov** [comment]
We cannot anyways possibly know which tips belong to this account before claiming anyways. Another issue is that after claiming we know this URL is claimed by that account, but this does not grant them exclusive ownership of the URL - at any moment anyone else can claim it if they have access to modify the HTML of the page which will render them the current `owner` of the URL.

I think this feature should be rethinked in general from UX perspective with regards to how the tipping/claiming works.

**Comment by mradkov** [comment]
resolved by #834
