### ISSUE TITLE
Seach input debounce

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#826]
Let's brainstorm this as the search currently sends a request immediately on each keypress which is not nearly efficient.

ref: http://underscorejs.org/#debounce

**Comment by davidyuk** [comment]
the same function should be in lodash, we just need to use it

**Comment by AtanasKrondev** [comment]
Shouldn't simple timeout in _SearchInput.vue_ do the trick?

`      set(query) {
        if (this.timeout) clearTimeout(this.timeout);
        this.timeout = setTimeout(() => {
          this.$router[this.$route.name.startsWith('tips') ? 'replace' : 'push']({
            name: query ? 'tips-search' : 'tips', params: { query },
          });
        }, 500);
      },`

**Comment by davidyuk** [comment]
won't to use debounce be simpler?

**Comment by mradkov** [comment]
@davidyuk @AtanasKrondev lets then use lodash if its easier.

**Comment by AtanasKrondev** [comment]
In both cases it's minimal additional code, but do we need to rely on library about this?

**Comment by davidyuk** [comment]
> In both cases it's minimal additional code

It is not true, in your implementation, there are two calls and 1 variable, but using lodash it is wrapped into one call (#835).

> do we need to rely on library about this?

I think yes, the library will make us use a consistent and well-known implementation between projects
