### ISSUE TITLE
Would be guards needed if we use plain links instead of buttons with click handler?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-ui#833]
https://github.com/aeternity/superhero-ui/pull/793/commits/df487ff492ff43ab942bd4a07f1b1136d1879ac9

Probably if we use plain links we won't be needed to write guards like in the commit above, making code simpler and more semantic.

**Comment by shapkarin** [comment]
@davidyuk look like it's not possible to separate links and handlers event inside links. In this case it will fires link navigation and event handler simultaneously. And for example at `src/components/tipRecords/TipComment.vue` when user clicks at tip button it will shows input but next page will be changed by link.
But I can try to avoid or change guards.

**Comment by davidyuk** [comment]
mostly resolved in #860
