### ISSUE TITLE
Different information in sh ui my profile and sh wallet 

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-ui#851]
When sh ui connected my wallet (extension) I see different balances on my profile and on the wallet. Seems that in my profile on sh ui are tokens  from the testnet.

![Знімок екрана 2020-10-15 о 5 57 17 пп](https://user-images.githubusercontent.com/69896204/96161877-846c6b00-0f20-11eb-9594-f66da2a23b8e.png)

**Comment by mradkov** [comment]
resolved by #849

**Comment by Liubov-crypto** [comment]
I have to refresh sh ui a couple of times before appears the right profile info.
When I refreshed sh page the wallet froze and appears this error:
![Знімок екрана 2020-10-16 о 10 40 43 дп](https://user-images.githubusercontent.com/69896204/96227858-61cc6780-0f9d-11eb-9b10-384e315355dd.png)

**Comment by Liubov-crypto** [comment]
The same issue is reproduced on FF and Brave:
![Знімок екрана 2020-10-16 о 12 03 42 пп](https://user-images.githubusercontent.com/69896204/96239735-c0e3a980-0fa8-11eb-8431-10ad6fcdd239.png)
![Знімок екрана 2020-10-16 о 12 03 58 пп](https://user-images.githubusercontent.com/69896204/96239763-c7722100-0fa8-11eb-968b-29142d7bddd1.png)

I have to refresh sh ui before appears the profile info.
