### ISSUE TITLE
Unexpected redirection from superhero.com/voting (my profile) to the superhero.com

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-ui#852]
It was hard to test all the voting options. After a couple of seconds on the superhero.com/voting, sh redirects me to superhero.com. I went back several times to superhero.com/voting to complete/start from scratch my transactions. 
The same unexpected behavior was on https://superhero.com/user-profile/, https://superhero.com/privacy and https://superhero.com/terms.

**Comment by mradkov** [comment]
Should be resolved by #849
