### ISSUE TITLE
Can't Tip User via icon on their profile/icon retip on the feed

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-ui#853]
The Blue Diamond on the user's avatar not active for tips. The same issue with icon on the sh feed for retips. They do not work.

![Знімок екрана 2020-10-15 о 6 29 36 пп](https://user-images.githubusercontent.com/69896204/96163949-34db6e80-0f23-11eb-96e3-e6e38ec478ee.png)
![Знімок екрана 2020-10-15 о 7 36 47 пп](https://user-images.githubusercontent.com/69896204/96163972-3c9b1300-0f23-11eb-9557-09eb59b50462.png)

**Comment by Liubov-crypto** [comment]
This issue is still reproducible on my side:
![Знімок екрана 2020-10-16 о 10 58 10 дп](https://user-images.githubusercontent.com/69896204/96228926-ebc90000-0f9e-11eb-9e99-b912253e24a6.png)
![Знімок екрана 2020-10-16 о 10 58 18 дп](https://user-images.githubusercontent.com/69896204/96228932-ef5c8700-0f9e-11eb-8828-04808a2bb224.png)
![Знімок екрана 2020-10-16 о 10 59 03 дп](https://user-images.githubusercontent.com/69896204/96228946-f2f00e00-0f9e-11eb-9f0d-036e1a33a2de.png)
![Знімок екрана 2020-10-16 о 10 59 15 дп](https://user-images.githubusercontent.com/69896204/96228957-f6839500-0f9e-11eb-893f-84ac8b6caaf5.png)
![Знімок екрана 2020-10-16 о 10 56 54 дп](https://user-images.githubusercontent.com/69896204/96228968-fa171c00-0f9e-11eb-97f5-3d5ffb2fec32.png)
![Знімок екрана 2020-10-16 о 10 57 04 дп](https://user-images.githubusercontent.com/69896204/96228976-fc797600-0f9e-11eb-95c1-8cb600afec30.png)

**Comment by Liubov-crypto** [comment]
The same issue on FF: 
![Знімок екрана 2020-10-16 о 11 50 04 дп](https://user-images.githubusercontent.com/69896204/96237410-f33fd780-0fa5-11eb-987a-470835adfd04.png)
![Знімок екрана 2020-10-16 о 11 50 16 дп](https://user-images.githubusercontent.com/69896204/96237457-fdfa6c80-0fa5-11eb-8fb5-55d21c961397.png)

![Знімок екрана 2020-10-16 о 11 53 05 дп](https://user-images.githubusercontent.com/69896204/96237778-61849a00-0fa6-11eb-8a74-4b8d56e4407a.png)
![Знімок екрана 2020-10-16 о 11 53 23 дп](https://user-images.githubusercontent.com/69896204/96237801-66494e00-0fa6-11eb-9ab9-bf157e5f430e.png)

**Comment by davidyuk** [comment]
should be fixed by #857 and #856

**Comment by Liubov-crypto** [comment]
Tested, now works on my side.
