### ISSUE TITLE
The disappearing button from settings

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-ui#865]
Youtube button disappeared from settings (Cookies policy) after I accepted Soundcloud.

1. Go to https://feature-cookies-settings.aggregator.z52da5wt.xyz/
2. Click on My Profile, click on Settings
3. Scroll down to Cookies policy
4. Click on Soundcloud button
5. Click on Confirm on pop-up
6. See error: 

![Знімок екрана 2020-10-27 о 12 27 13 пп](https://user-images.githubusercontent.com/69896204/97303286-e2734980-1862-11eb-87ac-1ac429a39d1f.png)

 - OS:  iOS 10.15.7
 - Browser  chrome
 - wallet: Superhero 9d084f9 / v.0.3.3

**Comment by CedrikNikita** [comment]
Current version of ui doesn't have such problem. Feel free to reopen this issue, if it will pop up in future.
