### ISSUE TITLE
The pop-up associated with the cookie policy appears several times

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-ui#866]
I enter settings on my profile to accept cookies and got this message several times.
I wanted to accept SoundCloud cookies and got this pop-up about 5 times.

Steps to reproduce the behaviour:

Go to https://feature-cookies-settings.aggregator.z52da5wt.xyz/
Click on My Profile, click on Settings
Scroll down to Cookies policy
Click on Soundcloud button
Click on Confirm on pop-up
See error:

![Знімок екрана 2020-10-27 о 1 46 00 пп](https://user-images.githubusercontent.com/69896204/97304240-23b82900-1864-11eb-9d65-ae01875bae0b.png)

OS: iOS 10.15.7
Browser chrome
wallet: Superhero 9d084f9 / v.0.3.3

**Comment by Liubov-crypto** [comment]
Checked on develop, LGTM. 
If in the wallet are ticks opposite "Don't ask for message signing", then pop-ups will not appear. If the user unchecks the boxes, pop-ups appear as they should - 1 time, to sign each transaction.

**Comment by CedrikNikita** [comment]
Current version of ui doesn't have such problem. Feel free to reopen this issue, if it will pop up in future.
