### ISSUE TITLE
Don't import store explicitly

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-ui#909]
https://github.com/aeternity/superhero-ui/blob/78572cc2834215b08900226e92790cc230dffb6f/src/utils/aeternity.js#L11

https://github.com/aeternity/superhero-ui/blob/ab19bbfc47534148b432e252e13eb5f39b9e4ae7/src/utils/backend.js#L2

Probably the best would be to rewrite backend.js and aeternity.js as Vuex modules. This refactoring is needed for SSR.

**Comment by davidyuk** [comment]
the related problem is a bit explained here: https://github.com/aeternity/superhero-ui/pull/901/files#r539518456

**Comment by shapkarin** [comment]
> https://github.com/aeternity/superhero-ui/pull/901/files#r539518456

thanks a lot

**Comment by shapkarin** [comment]
Compare with develop: https://github.com/aeternity/superhero-ui/compare/feature/aeternity_to_store

TODO: move Aeternity parts to the module https://vuex.vuejs.org/guide/modules.html

**Comment by davidyuk** [comment]
Well, the store is still imported in both `utils/aeternity.js` and `utils/backend.js`

**Comment by shapkarin** [comment]
> Well, the store is still imported in both `utils/aeternity.js` and `utils/backend.js`

thanks, didn't notice that. And, right, `utils/backend.js` also needs to be refactored.

**Comment by shapkarin** [comment]
@davidyuk think to add store `getters` later for the `modules/aeternity.js` and `modules/backend.js`.
looks like it can be useful.

**Comment by shapkarin** [comment]
@davidyuk @mradkov @CedrikNikita do you think `wrapTry` and `backendFetch` are should be an the store `actions`? 
I don't think so. 

What do you think? I already made them to be the actions but I think to revert that later.

https://github.com/aeternity/superhero-ui/blob/f484d2b4b4808a120218d2ebf564a7b59f67e0c9/src/utils/backend.js#L4-L22

https://github.com/aeternity/superhero-ui/blob/f484d2b4b4808a120218d2ebf564a7b59f67e0c9/src/utils/backend.js#L24-L26

**Comment by shapkarin** [comment]
@davidyuk @mradkov @CedrikNikita I also suggest to avoid Vue `mixins` as much as possible and use Vuex features instead.

**Comment by davidyuk** [comment]
fixed in #1115
