### ISSUE TITLE
Minor issue: Favicon has red background

### ISSUE THREAD

**Issue by thescientress** [aeternity/superhero-ui#916]
The favicon on mobile has a red background for some reason.

![_20201209_095857](https://user-images.githubusercontent.com/31926001/101564046-588fd200-3a05-11eb-95ec-84252e4457dc.JPG)

**Comment by davidyuk** [comment]
this is fixed in #913 
this icon has a black background now: https://develop.aggregator.z52da5wt.xyz/assets/apple-touch-icon-180x180.png
