### ISSUE TITLE
Tip input is not shown on User Profile page

### ISSUE THREAD

**Issue by stanislav-slavov** [aeternity/superhero-ui#919]
Steps to reproduce:
1. Go to User Profile page.
2. Click on Tip icon on the User avatar.

Expected:
A popup show up allowing the user to send AE tip to user profile url.

Actual:
The popup is not shown. There is an error in the console "cannot access id of undefined"

**Comment by mradkov** [comment]
Can you provide more info what this bug is? (screenshot also works)
