### ISSUE TITLE
Tipping via the retip button is broken on develop

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#924]
![Screen-Recording-2020-12-14-at-1](https://user-images.githubusercontent.com/13139371/102067060-4a75f300-3e03-11eb-90a3-1823781aa4ad.gif)

**Comment by stanislav-slavov** [comment]
This error is show on testnet. 
The problem is within the configurations used. There are 2 different contracts used for V1 tipping on testnet.
Using the same V1 contract for tipping/retipping would resolve the issue. No other action is required.
