### ISSUE TITLE
Records with only FT tips do not show the accumulated value

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#925]
![Screen-Recording-2020-12-14-at-1(2)](https://user-images.githubusercontent.com/13139371/102072101-10f4b600-3e0a-11eb-94c6-3ef6f69ed9b7.gif)

**Comment by onvisions** [comment]
After syncing with Stan we came to the following:

1. If there are no previous AE tips but we have other token tips we display next to the diamond icon (and before the dropdown arrow) the token tip with highest value (currently number of tokens but later when we can calculate their fiat value it will be the tip with highest current fiat value).
So we have Diamond, Tip value (+ fiat value in the brackets which is currently $ 0.00 for tokens other than AE but remains as placeholder), Dropdown arrow (if there are more token tips). Later if the item gets tipped with AE the AE value is shown first after the diamond by default.

2. Token tips are shown in the dropdown ordered by their value (number of tokens at the moment, fiat value in the future).

3. The dropdown should be limited in height, it should have vertical scrolling applied dealing with longer token tip lists.


@mradkov , @stanislav-slavov if you have objections please comment here.

**Comment by davidyuk** [comment]
> Token tips are shown in the dropdown ordered by their value (number of tokens at the moment, fiat value in the future).

Proposing to don't sort until fiat values available because it will make the most garbage tokens to bubble up in the list of tokens.
