### ISSUE TITLE
more specific configs inherit the general one, so no need to specify `VUE_APP_IMGUR_API_CLIENT_ID`, `VUE_APP_GIPHY_API_KEY ` as far as they are the same in `.env`

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#932]
more specific configs inherit the general one, so no need to specify `VUE_APP_IMGUR_API_CLIENT_ID`, `VUE_APP_GIPHY_API_KEY ` as far as they are the same in `.env`

_Originally posted by @davidyuk in https://github.com/aeternity/superhero-ui/pull/889#discussion_r543247550_

**Comment by AtanasKrondev** [comment]
[Fixed](https://github.com/aeternity/superhero-ui/blob/develop/.env.e2e)
