### ISSUE TITLE
Use `async`/`await` in post without tips

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#933]
Use `async`/`await` instead

_Originally posted by @davidyuk in https://github.com/aeternity/superhero-ui/pull/889#discussion_r543251562_

**Comment by AtanasKrondev** [comment]
It was already fixed in the feature before the merge. Should it be done in the whole project?

**Comment by mradkov** [comment]
No, it was only related to the posting without tips. Thanks. I'm closing this issue then.
