### ISSUE TITLE
Slow loading on develop

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#987]
![ezgif-7-6daf12bf3569](https://user-images.githubusercontent.com/13139371/105322254-48a50980-5bd1-11eb-8d44-d6ff69376f98.gif)

https://develop.aggregator.z52da5wt.xyz/

Chromium: Version 89.0.4360.0 (Developer Build) (x86_64)

**Comment by mradkov** [comment]
Could be something on my env, as nobody else was able to reproduce this. 🤔

**Comment by shapkarin** [comment]
@mradkov works well on my env

**Comment by mradkov** [comment]
> Could be something on my env, as nobody else was able to reproduce this. 🤔

Closing.
