### ISSUE TITLE
WordBazaar - Token does not appear after creation

### ISSUE THREAD

**Issue by imollov** [aeternity/superhero-ui#991]
Users should be informed about the standard delay for the newly created token to appear in the list. Or else the user may think something went wrong.

Alternatively, an optimistic rendering approach could be beneficial for this scenario.

**Comment by mradkov** [comment]
cc @thepiwo @onvisions

**Comment by thepiwo** [comment]
what commit version are you using, were there any errors in the console?

**Comment by imollov** [comment]
https://prototype-word-bazzar.aggregator.z52da5wt.xyz/wordbazaar

Some errors were thrown throughout the creation process, though they don't seem to be related:
![Screenshot 2021-01-22 at 13 08 39](https://user-images.githubusercontent.com/482351/105483743-f805dd00-5cb2-11eb-8883-bf7541b147e4.png)

**Comment by mradkov** [comment]
I think this issue is resolved already, it was caused by using different testing registry contract.
