### ISSUE TITLE
Avoid mixins or at least refact backendAuthMixin.js

### ISSUE THREAD

**Issue by shapkarin** [aeternity/superhero-ui#992]
I thinks that better is to avoid `eventBus` and replace it with `Vuex features`. 
It can help to make the app more useful and predictable for the development.

**Comment by shapkarin** [comment]
Also I think that some mixins can be replaced but to completely sure about that.

**Comment by davidyuk** [comment]
duplicate of #660

**Comment by shapkarin** [comment]
@davidyuk great! I will change this issue to the avoid `mixins`.
It's related to the https://github.com/aeternity/superhero-ui/pull/993#issuecomment-767239542

**Comment by shapkarin** [comment]
For example I plan to replace the `backendAuthMixin` [in that way](https://github.com/aeternity/superhero-ui/pull/993#issuecomment-767592659)

**Comment by shapkarin** [comment]
@davidyuk I think that mixins are fine. we just need to refact the `backendAuthMixin.js` somehow. I will close this issue
